# Generated by Django 6.0.3 on 2026-03-26 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('attending_physician', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('disease', 'Disease'), ('symptom', 'Symptom'), ('medication', 'Medication'), ('procedure', 'Procedure'), ('lab_test', 'Lab Test'), ('anatomy', 'Anatomy'), ('gene', 'Gene')], db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('node_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_medical_history', models.TextField(blank=True, default='')),
                ('medications_on_admission', models.TextField(blank=True, default='')),
                ('physical_examination', models.TextField(blank=True, default='')),
                ('lab_results', models.TextField(blank=True, default='')),
                ('imaging_results', models.TextField(blank=True, default='')),
                ('hospital_course', models.TextField()),
                ('discharge_diagnosis', models.TextField(blank=True, default='')),
                ('discharge_medications', models.TextField(blank=True, default='')),
                ('follow_up_instructions', models.TextField(blank=True, default='')),
                ('full_summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Discharge summaries',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_entities', models.JSONField(default=dict, help_text='BioBERT extracted entities')),
                ('graph_context', models.JSONField(default=dict, help_text='GraphRAG retrieved context')),
                ('primary_diagnosis', models.TextField()),
                ('secondary_diagnoses', models.JSONField(default=list)),
                ('diagnosis_confidence', models.FloatField(default=0.0)),
                ('diagnosis_reasoning', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('medications_recommended', models.JSONField(default=list)),
                ('procedures_recommended', models.JSONField(default=list)),
                ('lifestyle_modifications', models.JSONField(default=list)),
                ('follow_up_schedule', models.JSONField(default=list)),
                ('models_used', models.JSONField(default=list, help_text='List of AI models used')),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('pipeline_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discharge_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.dischargesummary')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('causes', 'Causes'), ('treats', 'Treats'), ('symptom_of', 'Symptom Of'), ('diagnosed_by', 'Diagnosed By'), ('contraindicated', 'Contraindicated'), ('interacts_with', 'Interacts With'), ('associated_with', 'Associated With'), ('preceded_by', 'Preceded By')], db_index=True, max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='patients.knowledgegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='patients.knowledgegraphnode')),
            ],
            options={
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
    ]
